import { GovernanceGate, Recommendation, UseCase } from "@/types";
import { GOVERNANCE_TEMPLATES } from "@/lib/governance";

export function buildADRContent(
  useCase: UseCase,
  recommendation: Recommendation,
  gate: GovernanceGate,
  version: number
): string {
  const template = GOVERNANCE_TEMPLATES[useCase.riskTier];
  const createdAt = new Date().toISOString();

  return `# Architecture Decision Record: ${useCase.title}

**Status:** ${gate.acknowledged ? "Approved" : "Pending governance sign-off"}
**Version:** v${version} (governance template v${template.version}, supersedes v${template.supersedes ?? "-"})
**Date:** ${createdAt}
**Owner:** ${useCase.owner}
**Steward:** ${useCase.steward}

## Use Case

${useCase.description}

- **Business domain:** ${useCase.businessDomain}
- **Data sensitivity:** ${useCase.dataSensitivity}
- **Agent autonomy level:** ${useCase.autonomyLevel}
- **Integration surface:** ${useCase.integrationSurface}
- **Expected users:** ${useCase.expectedUsers}

## Risk Classification (OSCAR - Classification)

**Computed risk tier: ${useCase.riskTier}**

This tier was computed deterministically from data sensitivity, agent autonomy,
and blast radius. It was not selected by the requester.

## Recommendation

- **Framework:** ${recommendation.framework}
- **Tool stack:** ${recommendation.tools.join(", ")}
- **Harness pattern:** ${recommendation.harnessPattern}
- **Loop pattern:** ${recommendation.loopPattern} (iteration ceiling: ${recommendation.iterationCeiling})
- **Context window strategy:** ${recommendation.contextStrategy}

**Rationale:**

${recommendation.rationale}

## Governance Gate (OSCAR - Ownership, Stewardship, Auditability)

- **HITL tier:** ${gate.hitlTier}
- **Required approvals:** ${template.requiredApprovals.join(", ")}
- **Required controls:**
${gate.requiredControls.map((c) => `  - ${c}`).join("\n")}
- **Acknowledged:** ${gate.acknowledged ? "Yes - all required items confirmed" : "No - blocking"}${
    gate.requiresArbApproval
      ? `\n- **Architecture Review Board sign-off:** ${
          gate.arbApproved
            ? `Approved by ${gate.arbApprovedBy} on ${gate.arbApprovedAt}`
            : "Pending - blocking"
        }`
      : ""
  }
- **Recertification interval:** ${template.recertificationDays ? `${template.recertificationDays} days` : "Not required at this tier"}

## Retain-and-Reinvent

This governance template is versioned (v${template.version}), superseding v${template.supersedes ?? "-"}.
Standards evolve; this ADR reflects the ruleset in effect at time of decision, not
an immutable requirement.

---
*Auto-generated by the Enterprise AI Governance & Framework Advisor. Traceable to OSCAR framework sections O/S/C/A/R.*
`;
}
