import { MCPServerEntry, ModelRegistryEntry } from "@/types";

// One-time seed source for the real DB-backed Model Registry
// (prisma/seed.ts) - not read by the running app itself, which reads
// ModelRegistryEntry/McpServerEntry straight from the database
// (src/app/api/admin/model-registry, src/app/api/admin/mcp-servers).
export const MODEL_REGISTRY: ModelRegistryEntry[] = [
  {
    id: "claude-sonnet-4-6",
    name: "Claude Sonnet 4.6",
    vendor: "Anthropic",
    version: "4.6",
    status: "approved",
    allowedRiskTiers: ["Low", "Medium", "High", "Critical"],
    changeReason: "Vendor's flagship general-purpose model with the strongest track record on Critical-tier use cases in this org's own past executions - approved for every risk tier.",
  },
  {
    id: "claude-opus-4-6",
    name: "Claude Opus 4.6",
    vendor: "Anthropic",
    version: "4.6",
    status: "approved",
    allowedRiskTiers: ["Low", "Medium", "High", "Critical"],
    changeReason: "Highest-capability tier for the hardest reasoning steps; approved everywhere given the same vendor security review already covering Sonnet.",
  },
  {
    id: "claude-haiku-4-5",
    name: "Claude Haiku 4.5",
    vendor: "Anthropic",
    version: "4.5",
    status: "approved",
    allowedRiskTiers: ["Low", "Medium"],
    changeReason: "Fast/cheap tier appropriate for high-volume, low-stakes steps; capped at Medium since it hasn't been validated on Critical-tier reasoning patterns.",
  },
  {
    id: "gpt-4o",
    name: "GPT-4o",
    vendor: "OpenAI",
    version: "2024-11",
    status: "approved",
    allowedRiskTiers: ["Low", "Medium", "High"],
    changeReason: "Second real fallback provider so the platform isn't single-vendor; not yet extended to Critical pending a dedicated security review for that tier.",
  },
  {
    id: "gpt-4o-mini",
    name: "GPT-4o mini",
    vendor: "OpenAI",
    version: "2024-11",
    status: "approved",
    allowedRiskTiers: ["Low", "Medium"],
    changeReason: "Cheap fallback tier mirroring Haiku's scope for the same reason - capped at Medium.",
  },
  {
    id: "gemini-1-5-pro",
    name: "Gemini 1.5 Pro",
    vendor: "Google",
    version: "1.5",
    status: "under-review",
    allowedRiskTiers: ["Low", "Medium"],
    changeReason: "Candidate third provider for redundancy - held at under-review until its own data-handling terms are checked against the same bar Anthropic/OpenAI already cleared.",
  },
  {
    id: "llama-3-1-405b",
    name: "Llama 3.1 405B",
    vendor: "Meta (self-hosted)",
    version: "3.1",
    status: "under-review",
    allowedRiskTiers: ["Low"],
    changeReason: "Self-hosted option evaluated for data-residency-sensitive use cases; restricted to Low tier only until self-hosted infra has its own security review.",
  },
  {
    id: "claude-2-1",
    name: "Claude 2.1",
    vendor: "Anthropic",
    version: "2.1",
    status: "deprecated",
    allowedRiskTiers: [],
    changeReason: "Superseded by Claude Sonnet/Opus 4.6 on every real metric this platform tracks (cost, latency, quality) - no use case should still declare this.",
  },
  {
    id: "gpt-3-5-turbo",
    name: "GPT-3.5 Turbo",
    vendor: "OpenAI",
    version: "0125",
    status: "deprecated",
    allowedRiskTiers: [],
    changeReason: "Superseded by GPT-4o/4o-mini on every real metric this platform tracks - no use case should still declare this.",
  },
];

export const MCP_SERVERS: MCPServerEntry[] = [
  {
    id: "mcp-filesystem",
    name: "Filesystem MCP Server",
    publisher: "Anthropic (reference)",
    description: "Exposes read/write access to a sandboxed directory tree as MCP tools.",
    status: "approved",
    allowedRiskTiers: ["Low", "Medium", "High"],
  },
  {
    id: "mcp-github",
    name: "GitHub MCP Server",
    publisher: "GitHub",
    description: "Repository, issue, and PR operations exposed as MCP tools for coding agents.",
    status: "approved",
    allowedRiskTiers: ["Low", "Medium", "High"],
  },
  {
    id: "mcp-postgres",
    name: "PostgreSQL MCP Server",
    publisher: "Community",
    description: "Read-only schema introspection and query execution against a Postgres database.",
    status: "approved",
    allowedRiskTiers: ["Low", "Medium"],
  },
  {
    id: "mcp-slack",
    name: "Slack MCP Server",
    publisher: "Community",
    description: "Send messages and read channel history through a scoped Slack bot token.",
    status: "under-review",
    allowedRiskTiers: ["Low", "Medium"],
  },
  {
    id: "mcp-internal-data",
    name: "Internal Data Platform MCP Server",
    publisher: "EGPA (internal)",
    description: "In-house server exposing approved internal data sources as governed MCP tools.",
    status: "under-review",
    allowedRiskTiers: ["Low"],
  },
  {
    id: "mcp-legacy-soap",
    name: "Legacy SOAP Bridge MCP Server",
    publisher: "EGPA (internal)",
    description: "Deprecated wrapper around a retired SOAP integration layer.",
    status: "deprecated",
    allowedRiskTiers: [],
  },
];
