import { MCPServerEntry, ModelRegistryEntry } from "@/types";

export const MODEL_REGISTRY: ModelRegistryEntry[] = [
  {
    id: "claude-sonnet-4-6",
    name: "Claude Sonnet 4.6",
    vendor: "Anthropic",
    version: "4.6",
    status: "approved",
    allowedRiskTiers: ["Low", "Medium", "High", "Critical"],
  },
  {
    id: "claude-opus-4-6",
    name: "Claude Opus 4.6",
    vendor: "Anthropic",
    version: "4.6",
    status: "approved",
    allowedRiskTiers: ["Low", "Medium", "High", "Critical"],
  },
  {
    id: "claude-haiku-4-5",
    name: "Claude Haiku 4.5",
    vendor: "Anthropic",
    version: "4.5",
    status: "approved",
    allowedRiskTiers: ["Low", "Medium"],
  },
  {
    id: "gpt-4o",
    name: "GPT-4o",
    vendor: "OpenAI",
    version: "2024-11",
    status: "approved",
    allowedRiskTiers: ["Low", "Medium", "High"],
  },
  {
    id: "gpt-4o-mini",
    name: "GPT-4o mini",
    vendor: "OpenAI",
    version: "2024-11",
    status: "approved",
    allowedRiskTiers: ["Low", "Medium"],
  },
  {
    id: "gemini-1-5-pro",
    name: "Gemini 1.5 Pro",
    vendor: "Google",
    version: "1.5",
    status: "under-review",
    allowedRiskTiers: ["Low", "Medium"],
  },
  {
    id: "llama-3-1-405b",
    name: "Llama 3.1 405B",
    vendor: "Meta (self-hosted)",
    version: "3.1",
    status: "under-review",
    allowedRiskTiers: ["Low"],
  },
  {
    id: "claude-2-1",
    name: "Claude 2.1",
    vendor: "Anthropic",
    version: "2.1",
    status: "deprecated",
    allowedRiskTiers: [],
  },
  {
    id: "gpt-3-5-turbo",
    name: "GPT-3.5 Turbo",
    vendor: "OpenAI",
    version: "0125",
    status: "deprecated",
    allowedRiskTiers: [],
  },
];

export const MCP_SERVERS: MCPServerEntry[] = [
  {
    id: "mcp-filesystem",
    name: "Filesystem MCP Server",
    publisher: "Anthropic (reference)",
    description: "Exposes read/write access to a sandboxed directory tree as MCP tools.",
    status: "approved",
    allowedRiskTiers: ["Low", "Medium", "High"],
  },
  {
    id: "mcp-github",
    name: "GitHub MCP Server",
    publisher: "GitHub",
    description: "Repository, issue, and PR operations exposed as MCP tools for coding agents.",
    status: "approved",
    allowedRiskTiers: ["Low", "Medium", "High"],
  },
  {
    id: "mcp-postgres",
    name: "PostgreSQL MCP Server",
    publisher: "Community",
    description: "Read-only schema introspection and query execution against a Postgres database.",
    status: "approved",
    allowedRiskTiers: ["Low", "Medium"],
  },
  {
    id: "mcp-slack",
    name: "Slack MCP Server",
    publisher: "Community",
    description: "Send messages and read channel history through a scoped Slack bot token.",
    status: "under-review",
    allowedRiskTiers: ["Low", "Medium"],
  },
  {
    id: "mcp-internal-data",
    name: "Internal Data Platform MCP Server",
    publisher: "Momentum (internal)",
    description: "In-house server exposing approved internal data sources as governed MCP tools.",
    status: "under-review",
    allowedRiskTiers: ["Low"],
  },
  {
    id: "mcp-legacy-soap",
    name: "Legacy SOAP Bridge MCP Server",
    publisher: "Momentum (internal)",
    description: "Deprecated wrapper around a retired SOAP integration layer.",
    status: "deprecated",
    allowedRiskTiers: [],
  },
];
